version: "3.8"
services:
    test_db:
        image: postgres:latest
        volumes:
            - ./db-data:/var/lib/postgresql/data
        ports:
            - 5438:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test_db
        restart: unless-stopped


    api:
        build:
            context: api/
            dockerfile: Dockerfile
        container_name: api
        depends_on:
            - test_db
        volumes:
            - ./api:/App
        ports:
            - 5001:5000
        environment:
            - ENV=dev
            - PYTHONPATH=/app
            - SECRET_KEY=MishSecretForLocal
            - DATABASE_URL=postgresql://postgres:test@test_db/test_db
            - API_ADDRESS=http://0.0.0.0:5000/
            - PYTHONUNBUFFERED=TRUE
        tty: true

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: admin_container
        depends_on:
            - test_db
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@mail.com
            - PGADMIN_DEFAULT_PASSWORD=pgadmin
        volumes:
            - ./db-data:/root/.pgadmin
        ports:
            - 84:80
        restart: unless-stopped

