version: "3.2"
services:
    test_db:
        image: postgres:latest
        volumes:
            - ./db-data:/var/lib/postgresql/data
        ports:
            - 5435:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=copia
            - POSTGRES_DB=test
        restart: unless-stopped


    api:
        build:
            context: api/
            dockerfile: Dockerfile
        container_name: taya_api
        depends_on:
            - tatay_db
        volumes:
            - ./api:/Taya
        expose:
            - 5000
        environment:
            - ENV=dev
            - PYTHONPATH=/app
            - SECRET_KEY=TayaSecretForLocal
            - DATABASE_URL=postgresql://postgres:copia@test_db/test_db
            - API_ADDRESS=http://0.0.0.0:5000/api
        tty: true
